# Generated by Django 5.1.6 on 2025-02-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_images/default_user_profile_picture.png', upload_to='profile_images/'),
        ),
    ]
